language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.1.502

services:
- docker

addons:
  apt:
    packages:
    - sshpass

install:
- dotnet restore

script:
- dotnet --info
- dotnet publish ContestantRegister --output ../_publish --configuration Release --runtime debian.8-x64
- echo v$TRAVIS_BUILD_NUMBER > ./_publish/wwwroot/version.txt

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
  bash ./.scripts/build-image.sh;
  bash ./.scripts/push-image.sh;
  bash ./.scripts/push-scripts.sh;
  bash ./.scripts/run-deploy-to-staging.sh;
  else
  echo Skip deply for $TRAVIS_BRANCH;
  fi
