language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.1.4

services:
- docker

addons:
  apt:
    packages:
    - sshpass

install:
- dotnet restore

script:
- dotnet --info
- dotnet publish ContestantRegister --output ../_publish --configuration Release --runtime debian.8-x64

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_EVENT_TYPE" != "pull_request" ]; then
  docker build --tag ikitsfu/contestantregister:staging --tag ikitsfu/contestantregister:$TRAVIS_BUILD_NUMBER .;
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  docker push ikitsfu/contestantregister:staging;
  docker push ikitsfu/contestantregister:$TRAVIS_BUILD_NUMBER;
  echo redeploy $HOST_USERNAME@$HOST_ADDRESS;
  export SSHPASS=$HOST_PASSWORD;
  sshpass -e ssh -o stricthostkeychecking=no $HOST_USERNAME@$HOST_ADDRESS "bash restart-app-staging.sh";
  echo redeploy completed;
  else
  echo $TRAVIS_BRANCH;
  fi
